### ISSUE TITLE
libmemcached dependency on libcloog-ppl0

### ISSUE THREAD

**Issue by fiterbek** [zodb/zodbshootout#1]
When following the README file to install zodbshootout, bin/buildout fails while building (lib)memcached with the following (partial) traceback: 

```
....
libmemcached/backtrace.cc: In function 'void custom_backtrace()':
libmemcached/backtrace.cc:57:6: sorry, unimplemented: Graphite loop optimizations can only be used if the libcloog-ppl0 package is installed
make[1]: *** [libmemcached/libmemcached_libmemcachedutil_la-backtrace.lo] Error 1
make[1]: Leaving directory `/opt/test/tmp/tmp_PnL6Bbuildout-libmemcached/libmemcached-1.0.10'
make: *** [all] Error 2
libmemcached: cmmi failed: /opt/test/tmp/tmp_PnL6Bbuildout-libmemcached
While:
  Installing libmemcached.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/opt/test/zodbshootout-0.5/lib/python2.6/site-packages/zc.buildout-2.2.1-py2.6.egg/zc/buildout/buildout.py", line 1942, in main
    getattr(buildout, command)(args)
  File "/opt/test/zodbshootout-0.5/lib/python2.6/site-packages/zc.buildout-2.2.1-py2.6.egg/zc/buildout/buildout.py", line 622, in install
    installed_files = self[part]._call(recipe.install)
  File "/opt/test/zodbshootout-0.5/lib/python2.6/site-packages/zc.buildout-2.2.1-py2.6.egg/zc/buildout/buildout.py", line 1366, in _call
    return f()
  File "/opt/test/zodbshootout-0.5/eggs/zc.recipe.cmmi-1.3.5-py2.6.egg/zc/recipe/cmmi/__init__.py", line 113, in install
    self.build()
  File "/opt/test/zodbshootout-0.5/eggs/zc.recipe.cmmi-1.3.5-py2.6.egg/zc/recipe/cmmi/__init__.py", line 196, in build
    self.cmmi(dest)
  File "/opt/test/zodbshootout-0.5/eggs/zc.recipe.cmmi-1.3.5-py2.6.egg/zc/recipe/cmmi/__init__.py", line 222, in cmmi
    system("make")
  File "/opt/test/zodbshootout-0.5/eggs/zc.recipe.cmmi-1.3.5-py2.6.egg/zc/recipe/cmmi/__init__.py", line 34, in system
    raise SystemError("Failed", c)
SystemError: ('Failed', 'make')
```

Installing libcloog-ppl0 using `(sudo) apt-get install libcloog-ppl0` fixed the problem, after that buildout ran like a charm. 

Since this package is not listed in the dependencies in setup.py nor the README file, I thought I'd mention this here. 

Kind regards, 

Frederic

**Comment by jamadden** [comment]
The installation instructions have been significantly overhauled. They now defer to the RelStorage docs for memcache information, which mentions that you need the development libraries appropriate to your platform.
